apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: wormhole
  name: wormhole
  namespace: insights
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: wormhole:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: git@github.com:jhjaggars/wormhole.git
    sourceSecret:
      name: nachobot
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: scratch
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
