irc:
  channels:
  - wormhole-testing
  - insights
  highlights:
    all:
    - - ping
      - insights
    satellite6:
    - 'insights '
    - 'insights:'
    sbr-sysmgmt:
    - 'insights '
    - 'insights:'
  highlights_destinations:
  - insights
  nick: wormhole
  port: 6667
  server: localhost
chanmaps: # slack <-> irc
  bottesting: wormhole-testing
